name: Automated STD Unit Testing

on:
  push:
    paths-ignore:
      - "**/README.md"
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  rust-checks:
    name: Rust Checks
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        action:
          - command: test
            args: -v --workspace --exclude focus --features unit-tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      # The .cargo folder contains configuration that do not work with running the test (probably dependency missing)
      # We only need the normal rust toolchain to test the STD Unit tests
      - name: Remove .cargo folder 
        run: rm -rf .cargo
      - name: Run tests
        # We use the stable toolchain to run the STD unit tests
        run: cargo +stable ${{ matrix.action.command }} ${{ matrix.action.args }}